/* Asia 2026 Family Challenge — stop data with per-player pools and arcade games.
   huntPool: 7 items, each player gets 5 (picked by their name).
   quizPool: 4 questions, each player gets 3.
   games: the 5 arcade mini-games for this stop. */
const STOPS=[
{id:'heathrow',lat:51.47,lng:-0.4543,day:'16 Oct 2026',unlock:'2026-01-01',emoji:'🛫',title:'London Heathrow',hotel:'Departure day',loc:'London, United Kingdom',
facts:['This is where the whole adventure begins!','Our flight KE908 to Seoul takes about 11 hours.','We fly Korean Air — Seoul first, then on to Tokyo tomorrow.'],
huntPool:['Find our flight on a departure board.','Spot a plane through the window.','Find our gate number.','Spot a shop selling Japanese or Korean snacks.','Find a sign pointing to departures.','Spot a pilot or cabin crew member.','Find a plane with a colourful tail design.'],
games:[["catch","Baggage Blitz",{"good":["🧳","🎒"],"bad":["🧦"],"catcher":"🛒"}],["runner","Terminal Dash",{"p":"🛒","o":"🧳"}],["tap","Passport Stamp",{"t":"🛂"}],["simon","Boarding Call",{}],["dodge","Gate Rush",{"p":"🧍","o":"🛄"}]],
quizPool:[["Roughly how far is London to Seoul?","About 5,500 miles",["About 5,500 miles","About 900 miles","About 15,000 miles"]],["Which airline are we flying?","Korean Air",["Korean Air","Japan Airlines","Ryanair"]],["Tokyo is 8 hours AHEAD of London.","true"],["We fly straight to Tokyo with no stops.","false"]]},

{id:'incheon',lat:37.4602,lng:126.4407,day:'17 Oct 2026',unlock:'2026-10-17',emoji:'🛬',title:'Incheon Connection',hotel:'Hotel Monte Hermana Tokyo',loc:'Incheon, South Korea',
facts:['We land in Korea — but only to change planes!','Incheon is regularly voted one of the best airports in the world.','We come back here properly on 27 October.'],
huntPool:['Find a sign written in Korean (한글).','Spot the word SEOUL or INCHEON.','Find our next gate.','Spot something you would buy in Korea.','Find a Korean snack in a shop.','Spot a robot, screen or gadget you do not have at home.','Find a departure board showing Tokyo.'],
games:[["runner","Transfer Sprint",{"p":"🏃","o":"🧳"}],["memory","Hangul Match",{"icons":["🇰🇷","✈️","🛂","🍜","🧳","🛫"]}],["tap","Gate Change",{"t":"✈️"}],["hl","Boarding Cards",{}],["dodge","Trolley Dodge",{"p":"🧍","o":"🛒"}]],
quizPool:[["What is the Korean alphabet called?","Hangul",["Hangul","Kanji","Cyrillic"]],["Which city is Incheon airport next to?","Seoul",["Seoul","Busan","Tokyo"]],["Korea and Japan are in different time zones.","false"],["We are only passing through Korea today.","true"]]},

{id:'nihonbashi',lat:35.6836,lng:139.7745,day:'17 Oct 2026',unlock:'2026-10-17',emoji:'🏨',title:'Tokyo Base Camp',hotel:'Hotel Monte Hermana Tokyo',loc:'Nihonbashi, Tokyo',
facts:['One train from Narita, no changes — 65 minutes to Nihombashi.','Nihonbashi is the old merchant heart of Tokyo.','Our hotel sits on the Ginza Line, Tokyo’s oldest subway.'],
huntPool:['Find a konbini (7-Eleven, Lawson or FamilyMart).','Buy or spot an onigiri rice ball.','Find a vending machine.','Spot a sign in Japanese only.','Find the hotel room number.','Spot a train or subway sign.','Find something you have never seen in a British shop.'],
games:[["catch","Konbini Sweep",{"good":["🍙","🥪","🍡"],"bad":["🧻"],"catcher":"🧺"}],["memory","Konbini Match",{"icons":["🍙","🍜","🍡","🥤","🍵","🍱"]}],["tap","Vending Machine",{"t":"🥤"}],["whack","Suitcase Sort",{"mole":"🧳","decoy":"🎒"}],["timing","Elevator Stop",{}]],
quizPool:[["What is a konbini?","A Japanese convenience store",["A Japanese convenience store","A train","A temple"]],["Which train did we take from Narita?","Keisei Sky Access Express",["Keisei Sky Access Express","The Shinkansen","A tram"]],["Japanese convenience store food is famously good.","true"],["Nihonbashi is in Kyoto.","false"]]},

{id:'sensoji',lat:35.7148,lng:139.7967,day:'18 Oct 2026',unlock:'2026-10-18',emoji:'⛩️',title:'Senso-ji Temple',hotel:'Hotel Monte Hermana Tokyo',loc:'Asakusa, Tokyo',
facts:['Senso-ji is Tokyo’s oldest temple, founded in 645 AD.','The Kaminarimon gate has an enormous red paper lantern.','Nakamise-dori is 250m of stalls leading to the main hall.'],
huntPool:['Find the giant red lantern at Kaminarimon.','Waft the incense smoke over yourself.','Buy or spot a ningyo-yaki cake.','Find an omikuji fortune paper.','Spot someone in a kimono or yukata.','Find the five-storey pagoda.','Spot a temple guardian statue.'],
games:[["whack","Lantern Bop",{"mole":"🏮","decoy":"🪨"}],["catch","Senbei Catch",{"good":["🍘","🍡"],"bad":["🗞️"],"catcher":"🧺"}],["memory","Temple Match",{"icons":["⛩️","🏮","🍘","🎋","🪷","🔔"]}],["timing","Incense Smoke",{}],["tap","Omikuji Draw",{"t":"🎴"}]],
quizPool:[["What year was Senso-ji founded?","645 AD",["645 AD","1645","1945"]],["What is the big gate at the front called?","Kaminarimon — Thunder Gate",["Kaminarimon — Thunder Gate","Torii Gate","Shibuya Gate"]],["Senso-ji is the most visited religious site in the world.","true"],["Senso-ji was built last year.","false"]]},

{id:'kappabashi',lat:35.7122,lng:139.7889,day:'18 Oct 2026',unlock:'2026-10-18',emoji:'🔪',title:'Kappabashi Street',hotel:'Hotel Monte Hermana Tokyo',loc:'Asakusa, Tokyo',
facts:['800 metres of shops that supply Tokyo’s restaurants.','Famous for handmade knives and plastic food samples.','The fake food looks so real you want to eat it.'],
huntPool:['Find the most realistic plastic food.','Spot a Japanese kitchen knife.','Find a fake bowl of ramen.','Spot a sushi keyring or magnet.','Find the giant chef’s head statue.','Spot a shop selling only bowls.','Find the funniest fake dish.'],
games:[["catch","Sushi Sample Catch",{"good":["🍣","🍤","🍱"],"bad":["🔪"],"catcher":"🍽️"}],["memory","Fake Food Match",{"icons":["🍣","🍜","🍤","🍱","🍚","🥟"]}],["tap","Knife Sharpener",{"t":"🔪"}],["whack","Plate Stack",{"mole":"🍽️","decoy":"🫖"}],["hl","Price Tag Cards",{}]],
quizPool:[["What is Kappabashi famous for?","Restaurant supplies and fake food",["Restaurant supplies and fake food","Car parts","Clothes"]],["What are the plastic dishes in restaurant windows for?","Showing customers the menu",["Showing customers the menu","Feeding cats","Decoration only"]],["You can buy a fake bowl of ramen here.","true"],["Kappabashi is a beach.","false"]]},

{id:'skytree',lat:35.7101,lng:139.8107,day:'18 Oct 2026',unlock:'2026-10-18',emoji:'🗼',title:'Tokyo Skytree',hotel:'Hotel Monte Hermana Tokyo',loc:'Sumida, Tokyo',
facts:['At 634 metres it is the tallest tower in the world.','The number 634 sounds like "Musashi", the old name for this area.','The Solamachi mall at the base has over 300 shops.'],
huntPool:['Find the Skytree from far away.','Spot the Sumida River.','Find the highest point you can see from the deck.','Spot a boat on the river.','Find a Skytree souvenir.','Take a photo looking straight down.','Spot another famous Tokyo building from up there.'],
games:[["runner","Tower Climb",{"p":"🧗","o":"🏗️"}],["dodge","Sky Winds",{"p":"🗼","o":"💨"}],["timing","Skyline Snap",{}],["memory","Tokyo Views",{"icons":["🗼","🌉","🏙️","🗻","🌆","🚄"]}],["tap","Lift Buttons",{"t":"🛗"}]],
quizPool:[["How tall is Tokyo Skytree?","634 metres",["634 metres","300 metres","1,000 metres"]],["What is Skytree mainly used for?","Broadcasting TV and radio",["Broadcasting TV and radio","Storing water","Growing plants"]],["Skytree is the tallest tower in the world.","true"],["You can see Mount Fuji from Skytree on every single day.","false"]]},

{id:'ueno',lat:35.7112,lng:139.7745,day:'18 Oct 2026',unlock:'2026-10-18',emoji:'🛍️',title:'Ameyoko Market',hotel:'Hotel Monte Hermana Tokyo',loc:'Ueno, Tokyo',
facts:['Ameyoko runs 500m under and beside the railway tracks.','It started as a post-war black market and never went away.','Stallholders actually shout at you here — very un-Tokyo.'],
huntPool:['Find dried fish for sale.','Spot a stallholder shouting.','Find the cheapest snack you can.','Spot a train passing overhead.','Find fresh fruit being sold by the piece.','Spot a shop selling trainers.','Find the busiest spot in the market.'],
games:[["catch","Market Grab",{"good":["🍓","🍡","🐟"],"bad":["🦐"],"catcher":"🧺"}],["whack","Stall Shout",{"mole":"🗣️","decoy":"🪧"}],["runner","Under the Tracks",{"p":"🏃","o":"📦"}],["dice21","Market Dice 21",{}],["tap","Haggle Tap",{"t":"💴"}]],
quizPool:[["What was Ameyoko originally?","A post-war black market",["A post-war black market","A palace garden","A train depot"]],["What runs directly over Ameyoko?","The railway",["The railway","A motorway","A river"]],["Ameyoko is a covered shopping arcade under the train line.","true"],["Ameyoko is the quietest place in Tokyo.","false"]]},

{id:'meiji',lat:35.6764,lng:139.6993,day:'19 Oct 2026',unlock:'2026-10-19',emoji:'🌲',title:'Meiji Jingu Shrine',hotel:'Hotel Monte Hermana Tokyo',loc:'Shibuya, Tokyo',
facts:['175 acres of forest in the middle of Tokyo.','All 100,000 trees were planted by hand in 1920.','It is dedicated to Emperor Meiji and Empress Shoken.'],
huntPool:['Find the giant wooden torii gate.','Find the wall of sake barrels.','Spot a wooden ema prayer plaque.','Find the water basin and wash your hands properly.','Spot a Shinto priest or shrine maiden.','Find the quietest spot in the forest.','Spot a wedding party if you are lucky.'],
games:[["memory","Shrine Match",{"icons":["⛩️","🌲","🍶","🎎","🔔","🪷"]}],["timing","Torii Bow",{}],["catch","Sake Barrel Roll",{"good":["🍶"],"bad":["🪨"],"catcher":"🛒"}],["simon","Shrine Bells",{}],["tap","Ema Plaque",{"t":"🪧"}]],
quizPool:[["How many trees were planted at Meiji Jingu?","About 100,000",["About 100,000","About 500","About 10 million"]],["What do you walk through to enter a Shinto shrine?","A torii gate",["A torii gate","A drawbridge","A tunnel"]],["The whole Meiji Jingu forest was planted by hand.","true"],["Meiji Jingu is a Buddhist temple.","false"]]},

{id:'harajuku',lat:35.6702,lng:139.7027,day:'19 Oct 2026',unlock:'2026-10-19',emoji:'🎀',title:'Harajuku · Takeshita-dori',hotel:'Hotel Monte Hermana Tokyo',loc:'Harajuku, Tokyo',
facts:['350 metres of teen fashion, crepes and rainbow candyfloss.','Harajuku style has influenced fashion all over the world.','Purikura photo booths let you edit yourself into a cartoon.'],
huntPool:['Find rainbow candyfloss.','Spot the wildest outfit on the street.','Find a crepe stand.','Spot a shop selling only socks.','Find something bright pink.','Take a purikura photo.','Find the strangest thing for sale.'],
games:[["catch","Crepe Catch",{"good":["🍓","🍌","🍫"],"bad":["🧅"],"catcher":"🥞"}],["tap","Purikura Snap",{"t":"📸"}],["memory","Kawaii Match",{"icons":["🎀","🍭","🌈","🧸","🍓","⭐"]}],["dodge","Crowd Surf",{"p":"🧍","o":"🛍️"}],["whack","Candy Grab",{"mole":"🍬","decoy":"🧅"}]],
quizPool:[["What is Takeshita-dori famous for?","Teen fashion and street food",["Teen fashion and street food","Car showrooms","Fishing boats"]],["What is a purikura?","A photo booth that edits your picture",["A photo booth that edits your picture","A noodle dish","A train"]],["Harajuku style is known around the world.","true"],["Takeshita-dori is a motorway.","false"]]},

{id:'shibuya',lat:35.6595,lng:139.7005,day:'19 Oct 2026',unlock:'2026-10-19',emoji:'🚦',title:'Shibuya Crossing',hotel:'Hotel Monte Hermana Tokyo',loc:'Shibuya, Tokyo',
facts:['The world’s busiest pedestrian crossing — up to 3,000 people per light.','Hachiko the dog waited nine years at the station for his owner.','Shibuya Parco’s 6th floor has Nintendo, Pokémon, Capcom and Jump stores.'],
huntPool:['Find the Hachiko statue.','Cross the crossing with everyone else.','Film the crossing from above.','Find the giant Mewtwo in the Pokémon Center.','Spot something Nintendo you cannot buy in the UK.','Find the busiest screen or billboard.','Spot a dog (real or statue).'],
games:[["dodge","Scramble Crossing",{"p":"🧍","o":"🚶"}],["tap","Crossing Rush",{"t":"🚦"}],["memory","Game Store Match",{"icons":["🍄","⚡","🎩","📕","🎮","👾"]}],["runner","Hachiko Run",{"p":"🐕","o":"🚧"}],["whack","Claw Machine",{"mole":"🧸","decoy":"🪙"}]],
quizPool:[["How many people can cross Shibuya Crossing on one light?","Up to 3,000",["Up to 3,000","About 50","About 100,000"]],["Who was Hachiko?","A loyal dog who waited for his owner",["A loyal dog who waited for his owner","An emperor","A video game"]],["Shibuya Crossing is the busiest pedestrian crossing in the world.","true"],["Hachiko was a cat.","false"]]},

{id:'shibuyasky',lat:35.6580,lng:139.7016,day:'19 Oct 2026',unlock:'2026-10-19',emoji:'🌇',title:'Shibuya Sky',hotel:'Hotel Monte Hermana Tokyo',loc:'Shibuya Scramble Square, Tokyo',
facts:['An open-air rooftop 229 metres up, 47 floors high.','There is no glass between you and the city.','On a clear day you can see Mount Fuji to the west.'],
huntPool:['Look straight down at Shibuya Crossing.','Find Tokyo Tower from up here.','Spot Mount Fuji if the sky is clear.','Lie down on the rooftop deck.','Take a photo at sunset.','Find Tokyo Skytree in the distance.','Spot the helipad.'],
games:[["timing","Sunset Snap",{}],["dodge","Rooftop Winds",{"p":"📷","o":"💨"}],["catch","Skyline Catch",{"good":["⭐","🌇"],"bad":["🌩️"],"catcher":"📷"}],["memory","City Lights",{"icons":["🌇","🗼","🗻","🏙️","🌃","✨"]}],["tap","Shutter Speed",{"t":"📸"}]],
quizPool:[["How high is the Shibuya Sky rooftop?","229 metres",["229 metres","634 metres","50 metres"]],["Why is 16:30 the best entry time?","You get daylight, sunset and night views",["You get daylight, sunset and night views","It is cheapest","It is the only slot"]],["Shibuya Sky is open-air with no glass.","true"],["You can wear a loose hat up there.","false"]]},

{id:'shinjuku',lat:35.6938,lng:139.7034,day:'19 Oct 2026',unlock:'2026-10-19',emoji:'🏮',title:'Shinjuku Neon',hotel:'Hotel Monte Hermana Tokyo',loc:'Shinjuku, Tokyo',
facts:['Shinjuku Station is the busiest railway station on Earth.','Omoide Yokocho is a lane of tiny post-war bars under the tracks.','Golden Gai has over 200 matchbox-sized bars in six alleys.'],
huntPool:['Find the biggest neon sign you can.','Spot the 3D cat billboard.','Find Omoide Yokocho (Memory Lane).','Spot a shop open 24 hours.','Find a sign with at least four colours.','Spot a robot, mascot or statue.','Find the narrowest alley you can walk down.'],
games:[["tap","Neon Tap",{"t":"🏮"}],["memory","Neon Match",{"icons":["🏮","🍜","🍢","🎌","🌃","🎰"]}],["dodge","Station Rush",{"p":"🧍","o":"🧳"}],["simon","Neon Sequence",{}],["catch","Yakitori Catch",{"good":["🍢","🍜"],"bad":["🦑"],"catcher":"🍱"}]],
quizPool:[["Which is the world’s busiest railway station?","Shinjuku",["Shinjuku","Tokyo Station","King’s Cross"]],["What is Omoide Yokocho?","A lane of tiny old bars and food stalls",["A lane of tiny old bars and food stalls","A shopping mall","A park"]],["Shinjuku’s neon signs are best seen after dark.","true"],["Golden Gai is a huge modern shopping centre.","false"]]},

{id:'tsukiji',lat:35.6654,lng:139.7707,day:'20 Oct 2026',unlock:'2026-10-20',emoji:'🐟',title:'Tsukiji Outer Market',hotel:'Hotel Monte Hermana Tokyo',loc:'Tsukiji, Tokyo',
facts:['Over 460 shops and stalls, open from about 5am.','The wholesale market moved to Toyosu in 2018 but this stayed.','Tamagoyaki on a stick is cooked right in front of you.'],
huntPool:['Find tamagoyaki being cooked.','Spot a whole tuna.','Find a strawberry daifuku.','Spot a knife shop.','Find the longest queue and ask what it is for.','Spot a stall selling only one thing.','Find something you would never eat.'],
games:[["catch","Tuna Catch",{"good":["🐟","🍣","🍙"],"bad":["🦐"],"catcher":"🧺"}],["whack","Tamagoyaki Flip",{"mole":"🍳","decoy":"🦑"}],["tap","Knife Skills",{"t":"🔪"}],["memory","Market Match",{"icons":["🐟","🍣","🍳","🍓","🍵","🍘"]}],["timing","Perfect Slice",{}]],
quizPool:[["Where did the wholesale fish market move to in 2018?","Toyosu",["Toyosu","Kyoto","Osaka"]],["What is tamagoyaki?","A sweet rolled omelette",["A sweet rolled omelette","A noodle soup","A rice ball"]],["Tsukiji Outer Market is mostly cash only.","true"],["Tsukiji is open late into the night.","false"]]},

{id:'teamlab',lat:35.6497,lng:139.7899,day:'20 Oct 2026',unlock:'2026-10-20',emoji:'🎨',title:'teamLab Planets',hotel:'Hotel Monte Hermana Tokyo',loc:'Toyosu, Tokyo',
facts:['You go barefoot and wade through knee-deep water.','Projected koi scatter when you touch them.','There are mirrored infinity rooms and a hall of floating orchids.'],
huntPool:['Take a photo in the mirror room.','Find the koi fish in the water.','Photograph the floating orchids.','Find the ball room with changing colours.','Take a photo of your feet in the water.','Spot the strangest room of all.','Find a reflection that goes on forever.'],
games:[["tap","Koi Touch",{"t":"🐟"}],["catch","Orchid Drop",{"good":["🌸","🌺"],"bad":["🪨"],"catcher":"🧺"}],["memory","Infinity Match",{"icons":["🌸","🐟","💧","✨","🔮","🌈"]}],["simon","Light Sequence",{}],["timing","Mirror Shot",{}]],
quizPool:[["What do you have to do before entering teamLab Planets?","Take off your shoes",["Take off your shoes","Wear a hat","Bring a torch"]],["What happens when you touch the projected koi?","They scatter away",["They scatter away","They stop moving","Nothing"]],["The QR code only appears on the day of your visit.","true"],["You should wear a long skirt to teamLab Planets.","false"]]},

{id:'toyosu',lat:35.6455,lng:139.7866,day:'20 Oct 2026',unlock:'2026-10-20',emoji:'🍣',title:'Toyosu & Senkyaku Banrai',hotel:'Hotel Monte Hermana Tokyo',loc:'Toyosu, Tokyo',
facts:['Toyosu is the working wholesale market that replaced Tsukiji’s inner market.','You watch the trading floor from glass walkways above.','Senkyaku Banrai is a rebuilt Edo-period food street from 2024.'],
huntPool:['Look down on the tuna trading floor.','Find the rooftop foot bath.','Spot a forklift or market vehicle.','Find a wooden Edo-style shopfront.','Eat something from a seafood counter.','Find a market worker in boots.','Spot the biggest fish in the building.'],
games:[["runner","Forklift Dash",{"p":"🚜","o":"📦"}],["catch","Auction Catch",{"good":["🐟","🍣"],"bad":["🦀"],"catcher":"🧊"}],["memory","Edo Street Match",{"icons":["🏮","🍣","🍵","🐟","🥢","♨️"]}],["dice21","Auction Dice 21",{}],["tap","Foot Bath",{"t":"♨️"}]],
quizPool:[["What time does the famous tuna auction happen?","About 5:30am",["About 5:30am","Midday","Midnight"]],["What period is Senkyaku Banrai built to look like?","The Edo period",["The Edo period","The 1980s","Ancient Egypt"]],["There is a free rooftop foot bath at Senkyaku Banrai.","true"],["Toyosu market is open every single day of the year.","false"]]},

{id:'odaiba',lat:35.6297,lng:139.7738,day:'20 Oct 2026',unlock:'2026-10-20',emoji:'🤖',title:'Odaiba',hotel:'Hotel Monte Hermana Tokyo',loc:'Tokyo Bay',
facts:['Odaiba is a man-made island in Tokyo Bay.','It has a replica Statue of Liberty with Rainbow Bridge behind it.','The Yurikamome train that gets you there is driverless.'],
huntPool:['Find the Statue of Liberty replica.','Photograph the Rainbow Bridge.','Sit at the very front of the driverless train.','Spot a boat in the bay.','Find an arcade machine you have never seen.','Take a photo with Tokyo’s skyline behind you.','Find the best view of the water.'],
games:[["runner","Yurikamome Run",{"p":"🚝","o":"🚧"}],["dodge","Bay Breeze",{"p":"🧍","o":"🌊"}],["tap","Arcade Frenzy",{"t":"🕹️"}],["memory","Bayside Match",{"icons":["🗽","🌉","🚝","🤖","🎮","🌊"]}],["reels","Odaiba Lights",{"icons":["🌉","🗽","🤖","🎮","⭐"]}]],
quizPool:[["What is unusual about the Yurikamome train?","It has no driver",["It has no driver","It flies","It runs on water"]],["What is Odaiba built on?","A man-made island",["A man-made island","A mountain","A bridge"]],["Odaiba has a copy of the Statue of Liberty.","true"],["Odaiba is in the mountains.","false"]]},

{id:'palace',lat:35.6852,lng:139.7528,day:'21 Oct 2026',unlock:'2026-10-21',emoji:'🏯',title:'Imperial Palace Gardens',hotel:'Hotel Monte Hermana Tokyo',loc:'Chiyoda, Tokyo',
facts:['These are the grounds of Edo Castle, the shogun’s stronghold.','The Imperial Family moved here in 1868.','You can climb the stone base of the tallest castle tower in Japanese history.'],
huntPool:['Climb the Tenshudai keep base.','Find the moat.','Photograph Nijubashi Bridge.','Spot a guard.','Find a huge stone in the wall.','Spot a black pine tree.','Find the Ninomaru garden.'],
games:[["runner","Castle Dash",{"p":"🥷","o":"🪨"}],["memory","Shogun Match",{"icons":["🏯","🗡️","🎌","🌸","🐉","🛡️"]}],["whack","Ninja Watch",{"mole":"🥷","decoy":"🌳"}],["timing","Gate Timing",{}],["hl","Samurai Cards",{}]],
quizPool:[["What castle stood here before the palace?","Edo Castle",["Edo Castle","Osaka Castle","Himeji Castle"]],["What destroyed the great keep in 1657?","A huge fire",["A huge fire","An earthquake","A flood"]],["The Imperial Family still lives on this site.","true"],["The East Gardens are open every day.","false"]]},

{id:'akihabara',lat:35.6984,lng:139.7731,day:'21 Oct 2026',unlock:'2026-10-21',emoji:'🎌',title:'Akihabara Electric Town',hotel:'Hotel Monte Hermana Tokyo',loc:'Akihabara, Tokyo',
facts:['Seven-storey buildings entirely full of anime and games.','Don Quijote has a giant illuminated penguin sign.','The neon on Chuo-dori only fully lights up after dark.'],
huntPool:['Find the Don Quijote penguin.','Win something from a claw machine.','Find a retro games shop.','Spot a building covered in anime art.','Find the tallest arcade tower.','Spot a vending machine selling something odd.','Photograph Chuo-dori after dark.'],
games:[["tap","Arcade Blitz",{"t":"🕹️"}],["whack","Claw Machine",{"mole":"🧸","decoy":"🪙"}],["memory","Anime Match",{"icons":["🎮","👾","🤖","🎌","📺","🕹️"]}],["simon","Rhythm Game",{}],["reels","Gacha Pull",{"icons":["🎮","🤖","👾","⭐","🎀"]}]],
quizPool:[["What is Akihabara nicknamed?","Electric Town",["Electric Town","Old Town","Fish Town"]],["What is a gachapon?","A capsule toy machine",["A capsule toy machine","A noodle shop","A train"]],["Akihabara’s neon is best seen after dark.","true"],["Akihabara is famous for farming.","false"]]},

{id:'kanda',lat:35.7021,lng:139.7679,day:'21 Oct 2026',unlock:'2026-10-21',emoji:'⛩️',title:'Kanda Myojin Shrine',hotel:'Hotel Monte Hermana Tokyo',loc:'Akihabara, Tokyo',
facts:['Founded in 730 AD — nearly 1,300 years old.','People bring laptops and hard drives here to be blessed.','It sells IT-protection amulets for your data.'],
huntPool:['Find the red and gold Zuishin-mon gate.','Spot an anime drawing on a prayer board.','Find the IT protection charm.','Spot the Akihabara skyline behind the shrine.','Find a stone lion-dog guardian.','Ring the bell properly.','Find the oldest-looking thing here.'],
games:[["memory","Amulet Match",{"icons":["⛩️","💻","🔔","🎴","🐉","✨"]}],["tap","Bless the Laptop",{"t":"💻"}],["catch","Omamori Catch",{"good":["🎴","🧧"],"bad":["💀"],"catcher":"🙏"}],["timing","Bell Ring",{}],["whack","Fox Spotter",{"mole":"🦊","decoy":"🪨"}]],
quizPool:[["When was Kanda Myojin founded?","730 AD",["730 AD","1730","1930"]],["What unusual charm does it sell?","An IT and data protection amulet",["An IT and data protection amulet","A driving licence","A train ticket"]],["It survived the 1945 firebombing because it was rebuilt in concrete.","true"],["Kanda Myojin is brand new.","false"]]},

{id:'shinkansen',lat:35.6812,lng:139.7671,day:'22 Oct 2026',unlock:'2026-10-22',emoji:'🚄',title:'Nozomi to Kyoto',hotel:'hotel androoms Kyoto Shichijo',loc:'Tokyo → Kyoto',
facts:['The Nozomi covers 500km in 2 hours 15 minutes.','Top speed is 285 km/h.','Mount Fuji appears on the right about 40 minutes in.'],
huntPool:['Spot Mount Fuji from seat D or E.','Photograph your ekiben lunch box.','Find the platform number sign.','Spot the train’s pointed nose.','Find the speed shown on the carriage screen.','Spot rice fields from the window.','Find a station you have never heard of.'],
games:[["runner","Bullet Train Run",{"p":"🚄","o":"🚧"}],["timing","Fuji Photo",{}],["catch","Ekiben Catch",{"good":["🍱","🍙","🍵"],"bad":["🗑️"],"catcher":"🧺"}],["memory","Shinkansen Match",{"icons":["🚄","🗻","🍱","🎫","🌾","🏔️"]}],["tap","Platform Dash",{"t":"🎫"}]],
quizPool:[["How fast does the Nozomi travel?","Up to 285 km/h",["Up to 285 km/h","100 km/h","600 km/h"]],["Which side should you sit on for Mount Fuji?","The right — seats D and E",["The right — seats D and E","The left","It does not matter"]],["An ekiben is a station lunch box.","true"],["The journey takes eight hours.","false"]]},

{id:'sanjusangendo',lat:34.9879,lng:135.7717,day:'22 Oct 2026',unlock:'2026-10-22',emoji:'🙏',title:'Sanjusangen-do',hotel:'hotel androoms Kyoto Shichijo',loc:'Higashiyama, Kyoto',
facts:['A 120-metre wooden hall founded in 1164.','Inside are 1,001 life-size gilded statues of Kannon.','Every single statue has a different face.'],
huntPool:['Count how many statues you can see at once.','Find the thunder god or wind god.','Walk the whole hall barefoot.','Find the oldest-looking statue.','Spot a statue with an unusual face.','Find the wooden floor joins.','Spot the garden outside.'],
games:[["memory","Kannon Match",{"icons":["🙏","🪷","🔔","🎋","🏯","✨"]}],["tap","Count the Statues",{"t":"🙏"}],["timing","Silent Step",{}],["simon","Temple Chant",{}],["hl","Statue Cards",{}]],
quizPool:[["How many Kannon statues are inside?","1,001",["1,001","101","10"]],["What are the statues carved from?","Japanese cypress wood",["Japanese cypress wood","Marble","Plastic"]],["Photography is banned inside the hall.","true"],["Every statue has exactly the same face.","false"]]},

{id:'jidai',lat:35.0116,lng:135.7681,day:'22 Oct 2026',unlock:'2026-10-22',emoji:'🎎',title:'Jidai Matsuri',hotel:'hotel androoms Kyoto Shichijo',loc:'Oike-dori, Kyoto',
facts:['The Festival of the Ages, held every 22 October since 1895.','About 2,000 people walk in historical costume.','The parade runs backwards through time — newest first, oldest last.'],
huntPool:['Find a samurai in armour.','Spot a Heian-era court costume.','Find someone carrying a banner.','Spot a horse in the parade.','Find the most elaborate costume.','Spot a musician or drummer.','Find someone in the crowd filming everything.'],
games:[["whack","Costume Spotter",{"mole":"🎎","decoy":"🪨"}],["memory","Era Match",{"icons":["🎎","🗡️","🏹","👘","🥁","🏮"]}],["tap","Parade Count",{"t":"🎌"}],["timing","Parade Photo",{}],["catch","Confetti Catch",{"good":["🌸","🎌"],"bad":["🪨"],"catcher":"🧺"}]],
quizPool:[["What does Jidai Matsuri mean?","Festival of the Ages",["Festival of the Ages","Festival of Fire","Festival of Snow"]],["What order does the parade run in?","Backwards through history",["Backwards through history","Alphabetical","Random"]],["Jidai Matsuri happens every 22 October.","true"],["The parade lasts five minutes.","false"]]},

{id:'nishiki',lat:35.0050,lng:135.7649,day:'22 Oct 2026',unlock:'2026-10-22',emoji:'🥢',title:'Nishiki Market',hotel:'hotel androoms Kyoto Shichijo',loc:'Central Kyoto',
facts:['Known as "Kyoto’s Kitchen" — five blocks long, four metres wide.','It has been trading for around 400 years.','Over 130 stalls sell pickles, tofu, tea and sweets.'],
huntPool:['Find Kyoto pickles (tsukemono).','Spot yuba (tofu skin).','Find matcha in three different forms.','Spot a knife shop.','Find the narrowest part of the arcade.','Buy or spot a Japanese sweet.','Find a stall that has been there for generations.'],
games:[["catch","Pickle Catch",{"good":["🥒","🍵","🍡"],"bad":["🐙"],"catcher":"🧺"}],["memory","Kyoto Kitchen",{"icons":["🍵","🥒","🍡","🥢","🍱","🍶"]}],["whack","Tofu Toss",{"mole":"🍢","decoy":"🐙"}],["tap","Matcha Whisk",{"t":"🍵"}],["dice21","Market Dice 21",{}]],
quizPool:[["What is Nishiki Market nicknamed?","Kyoto’s Kitchen",["Kyoto’s Kitchen","Kyoto’s Garden","Kyoto’s Castle"]],["Roughly how long has Nishiki been trading?","About 400 years",["About 400 years","About 20 years","About 4,000 years"]],["Nishiki Market is a covered arcade.","true"],["Nishiki Market is in Tokyo.","false"]]},

{id:'arashiyama',lat:35.0094,lng:135.6668,day:'23 Oct 2026',unlock:'2026-10-23',emoji:'🎋',title:'Arashiyama & Monkeys',hotel:'hotel androoms Kyoto Shichijo',loc:'Arashiyama, Kyoto',
facts:['The bamboo grove is about 500 metres long.','Tenryu-ji’s garden is the oldest in Japan in its original form.','At Iwatayama, 120 wild macaques roam free at the summit.'],
huntPool:['Photograph the bamboo grove.','Find the Togetsukyo Bridge.','Feed a monkey through the hut mesh.','Spot a baby monkey.','Find the view over Kyoto from the summit.','Spot a rickshaw.','Find the Tenryu-ji garden pond.'],
games:[["runner","Bamboo Run",{"p":"🏃","o":"🎋"}],["whack","Monkey Peekaboo",{"mole":"🐒","decoy":"🎋"}],["catch","Monkey Feed",{"good":["🍎","🥜"],"bad":["🪨"],"catcher":"🐒"}],["memory","Grove Match",{"icons":["🎋","🐒","🌉","🍁","🏯","🍵"]}],["dodge","Uphill Climb",{"p":"🥾","o":"🪨"}]],
quizPool:[["What kind of monkeys live at Iwatayama?","Japanese macaques",["Japanese macaques","Chimpanzees","Baboons"]],["Who is inside the cage at the monkey park?","The humans",["The humans","The monkeys","Nobody"]],["The Tenryu-ji garden is a UNESCO World Heritage site.","true"],["The bamboo grove is 10 kilometres long.","false"]]},

{id:'nijo',lat:35.0142,lng:135.7481,day:'23 Oct 2026',unlock:'2026-10-23',emoji:'🏯',title:'Nijo Castle',hotel:'hotel androoms Kyoto Shichijo',loc:'Nakagyo, Kyoto',
facts:['Built in 1603 for Tokugawa Ieyasu, the first shogun.','The nightingale floors chirp so no assassin can sneak in.','The last shogun handed power back to the Emperor here in 1867.'],
huntPool:['Try to cross a nightingale floor silently.','Find a gold-leaf screen painting.','Spot the shogun’s throne room.','Find the moat and stone walls.','Count the tatami mats in one room.','Spot a tiger or dragon painting.','Find the garden pond.'],
games:[["timing","Silent Step",{}],["whack","Nightingale Floor",{"mole":"🥷","decoy":"🏯"}],["memory","Shogun Match",{"icons":["🏯","🗡️","🐅","🐉","🎌","🪭"]}],["runner","Castle Escape",{"p":"🥷","o":"🗡️"}],["simon","Floor Squeaks",{}]],
quizPool:[["Why do the nightingale floors chirp?","To warn of intruders",["To warn of intruders","They are broken","For music"]],["Who built Nijo Castle?","Tokugawa Ieyasu",["Tokugawa Ieyasu","Emperor Meiji","Oda Nobunaga"]],["700 years of samurai rule ended in a room in this castle.","true"],["You can walk silently across a nightingale floor.","false"]]},

{id:'kiyomizu',lat:34.9949,lng:135.7850,day:'23 Oct 2026',unlock:'2026-10-23',emoji:'🏮',title:'Kiyomizu-dera & Gion',hotel:'hotel androoms Kyoto Shichijo',loc:'Higashiyama, Kyoto',
facts:['The great wooden stage was built in 1633 without a single nail.','At Otowa Waterfall you drink from one of three streams.','Sannenzaka and Ninenzaka are preserved stone-stepped lanes.'],
huntPool:['Stand on the wooden stage.','Drink from one stream at Otowa Waterfall.','Photograph the Yasaka Pagoda.','Find a lantern lit at dusk.','Spot someone in a kimono.','Find a matcha ice cream.','Photograph Sannenzaka without falling over.'],
games:[["dodge","Sannenzaka Steps",{"p":"👘","o":"🪨"}],["timing","Pagoda Photo",{}],["catch","Waterfall Cup",{"good":["💧"],"bad":["🍂"],"catcher":"🥄"}],["memory","Old Kyoto Match",{"icons":["🏮","⛩️","🍵","👘","🗼","🍁"]}],["tap","Lantern Light",{"t":"🏮"}]],
quizPool:[["How was the Kiyomizu-dera stage built?","Without a single nail",["Without a single nail","With concrete","With steel bolts"]],["What do the three streams at Otowa offer?","Longevity, love or success",["Longevity, love or success","Money, food or sleep","Nothing"]],["Tripping on Sannenzaka is said to bring three years’ bad luck.","true"],["You may photograph anywhere you like in Gion.","false"]]},

{id:'fushimi',lat:34.9671,lng:135.7727,day:'24 Oct 2026',unlock:'2026-10-24',emoji:'⛩️',title:'Fushimi Inari',hotel:'Sheraton Grande Tokyo Bay',loc:'Fushimi, Kyoto',
facts:['Thousands of vermilion torii gates form tunnels up a mountain.','It is open 24 hours a day and always free.','The foxes are messengers of Inari, the rice god.'],
huntPool:['Photograph a tunnel of torii gates.','Find a fox statue with a key in its mouth.','Read the writing on the back of a gate.','Reach the Yotsutsuji viewpoint.','Find the smallest torii gate.','Spot the city view over Kyoto.','Find a fox-shaped prayer plaque.'],
games:[["runner","Torii Run",{"p":"🏃","o":"⛩️"}],["whack","Fox Spotter",{"mole":"🦊","decoy":"🪨"}],["dodge","Mountain Path",{"p":"🥾","o":"🪨"}],["memory","Inari Match",{"icons":["⛩️","🦊","🍚","🏮","🔑","🌲"]}],["timing","Empty Shot",{}]],
quizPool:[["What animal is Inari’s messenger?","The fox",["The fox","The deer","The crane"]],["Why go at 7:20am?","It is almost empty then",["It is almost empty then","It closes at 8am","It is cheaper"]],["Fushimi Inari is free and open 24 hours.","true"],["There are only ten torii gates.","false"]]},

{id:'tokyobay',lat:35.6329,lng:139.8804,day:'24 Oct 2026',unlock:'2026-10-24',emoji:'🏊',title:'Tokyo Bay & The Pool',hotel:'Sheraton Grande Tokyo Bay',loc:'Maihama, Urayasu',
facts:['The Sheraton pool is 25 metres, heated and free for guests.','The Disney Resort monorail runs right past the hotel.','Tonight is the Disney briefing — tomorrow starts at 5am.'],
huntPool:['Photograph the hotel pool.','Find the Disney monorail.','Spot a Disney character somewhere in the hotel.','Find the Ikspiari shopping centre.','Spot a park guest already in costume.','Find the hotel shuttle stop.','Take a team photo before Disney.'],
games:[["catch","Pool Splash",{"good":["🏊","🦺"],"bad":["🧊"],"catcher":"🛟"}],["runner","Monorail Dash",{"p":"🚝","o":"🧳"}],["memory","Bayside Match",{"icons":["🏊","🚝","🏰","🌊","🛟","🎡"]}],["timing","Perfect Dive",{}],["tap","Lane Swim",{"t":"🏊"}]],
quizPool:[["How long is the Sheraton indoor pool?","25 metres",["25 metres","10 metres","100 metres"]],["Why is the swim on this day and not later?","The airport bus leaves before the pool opens on the last day",["The airport bus leaves before the pool opens on the last day","The pool shuts for winter","Nobody wanted to swim"]],["The indoor pool is free for hotel guests.","true"],["The outdoor Garden Pool is open in October.","false"]]},

{id:'disneyland',lat:35.6329,lng:139.8804,day:'25 Oct 2026',unlock:'2026-10-25',emoji:'🏰',title:'Tokyo Disneyland',hotel:'Sheraton Grande Tokyo Bay',loc:'Maihama, Urayasu',
facts:['Rope drop at 6:15am is worth more than any pass you can buy.','The free line-skip system ended in August 2026 — Premier Access is paid.','Haunted Mansion is running its Nightmare Before Christmas overlay.'],
huntPool:['Photograph Cinderella Castle.','Find a Halloween decoration.','Spot someone in full costume.','Find a popcorn flavour you have never seen.','Ride something before 8am.','Find a hidden Mickey.','Photograph the fireworks.'],
games:[["runner","Rope Drop Dash",{"p":"🏃","o":"🧳"}],["tap","Premier Access",{"t":"🎟️"}],["memory","Park Match",{"icons":["🏰","🎃","👻","🎠","🍿","🎆"]}],["whack","Hidden Mickey",{"mole":"🐭","decoy":"🎈"}],["timing","Firework Snap",{}]],
quizPool:[["What replaced the free line-skip system?","Paid Disney Premier Access",["Paid Disney Premier Access","Nothing","A lottery"]],["What is Haunted Mansion re-themed to?","The Nightmare Before Christmas",["The Nightmare Before Christmas","Frozen","Star Wars"]],["Premier Access is charged per person, per ride.","true"],["You can book Premier Access before you scan in at the gate.","false"]]},

{id:'disneysea',lat:35.6267,lng:139.8850,day:'26 Oct 2026',unlock:'2026-10-26',emoji:'🌊',title:'Tokyo DisneySea',hotel:'Sheraton Grande Tokyo Bay',loc:'Maihama, Urayasu',
facts:['DisneySea is unique to Tokyo and often rated the best Disney park on Earth.','Fantasy Springs opened in 2024 with Frozen, Tangled and Peter Pan.','Journey to the Center of the Earth is inside a volcano.'],
huntPool:['Photograph Mount Prometheus.','Find the Mediterranean Harbor at dusk.','Spot Miguel from Coco.','Find a ride you cannot get anywhere else.','Photograph a lantern in Rapunzel’s land.','Spot a gondola or boat.','Find the best view in the park.'],
games:[["runner","Volcano Escape",{"p":"🏃","o":"🌋"}],["catch","Lantern Catch",{"good":["🏮","✨"],"bad":["🌩️"],"catcher":"🧺"}],["memory","DisneySea Match",{"icons":["🌋","🏮","❄️","🧚","⛵","🎢"]}],["timing","Harbor Photo",{}],["dodge","Queue Dodge",{"p":"🧍","o":"⏳"}]],
quizPool:[["What is inside Mount Prometheus?","Journey to the Center of the Earth",["Journey to the Center of the Earth","A restaurant","A hotel"]],["Which ride sells out of Premier Access first?","Anna and Elsa’s Frozen Journey",["Anna and Elsa’s Frozen Journey","Toy Story Mania","Tower of Terror"]],["DisneySea exists only in Tokyo.","true"],["Fantasy Springs needs a separate ticket.","false"]]},

{id:'seoul',lat:37.5547,lng:126.9707,day:'27 Oct 2026',unlock:'2026-10-27',emoji:'🇰🇷',title:'Seoul Arrival',hotel:'ENA Suite Hotel Namdaemun',loc:'Namdaemun, Seoul',
facts:['The AREX Express runs Incheon to Seoul Station in 51 minutes.','Namdaemun is Korea’s oldest market district.','Korean convenience stores sell excellent tuna and cheese kimbap.'],
huntPool:['Find a sign written in Hangul.','Spot a GS25 or CU convenience store.','Buy or find kimbap.','Find Namdaemun market.','Spot a T-money card.','Find a Korean street food stall.','Spot something that is different from Japan.'],
games:[["runner","AREX Express",{"p":"🚄","o":"🧳"}],["catch","Kimbap Catch",{"good":["🍙","🥟","🍜"],"bad":["🦐"],"catcher":"🧺"}],["memory","Seoul Match",{"icons":["🇰🇷","🍙","🏯","🚇","🥟","🏮"]}],["tap","T-money Tap",{"t":"💳"}],["hl","Won Notes",{}]],
quizPool:[["How long does the AREX Express take to Seoul?","51 minutes",["51 minutes","5 minutes","3 hours"]],["Which terminal does Korean Air use at Incheon?","Terminal 2",["Terminal 2","Terminal 1","Terminal 5"]],["Korea is even more card-friendly than Japan.","true"],["UK passports need a K-ETA for this trip.","false"]]},

{id:'gyeongbokgung',lat:37.5796,lng:126.9770,day:'28 Oct 2026',unlock:'2026-10-28',emoji:'👘',title:'Gyeongbokgung Palace',hotel:'ENA Suite Hotel Namdaemun',loc:'Jongno, Seoul',
facts:['The main royal palace of the Joseon dynasty, founded in 1395.','Anyone wearing hanbok gets in free.','Today is Culture Day — the last Wednesday of the month — so entry is free anyway.'],
huntPool:['Photograph the throne hall.','Watch the Changing of the Royal Guard.','Find the Gyeonghoeru pavilion on its pond.','Wear hanbok and take a photo.','Spot a roof guardian figure.','Find the palace wall.','Photograph Namsan Tower from the grounds.'],
games:[["memory","Palace Match",{"icons":["🏯","👘","🥁","🎎","🐉","🏵️"]}],["timing","Guard Change",{}],["simon","Royal Drums",{}],["whack","Guard Spotter",{"mole":"💂","decoy":"🌳"}],["tap","Hanbok Twirl",{"t":"👘"}]],
quizPool:[["When was Gyeongbokgung founded?","1395",["1395","1895","1995"]],["What is hanbok?","Traditional Korean dress",["Traditional Korean dress","A Korean stew","A palace"]],["Wearing hanbok gets you into the palace free.","true"],["Gyeongbokgung is open on Tuesdays.","false"]]},

{id:'bukchon',lat:37.5826,lng:126.9830,day:'28 Oct 2026',unlock:'2026-10-28',emoji:'🏘️',title:'Bukchon Hanok Village',hotel:'ENA Suite Hotel Namdaemun',loc:'Jongno, Seoul',
facts:['Around 900 traditional hanok houses on a hillside.','The village is 600 years old and people still live in it.','The famous view is from Bukchon-ro 11-gil.'],
huntPool:['Photograph a hanok roof line.','Find the famous alley view.','Spot Namsan Tower behind the houses.','Find a "please be quiet" sign.','Spot a traditional door handle.','Find the steepest street.','Photograph the tiles on a roof.'],
games:[["dodge","Quiet Streets",{"p":"🧍","o":"📢"}],["memory","Hanok Match",{"icons":["🏘️","🏮","🎎","🍵","🌸","🪟"]}],["timing","Perfect Alley Shot",{}],["tap","Roof Tiles",{"t":"🏘️"}],["hl","House Cards",{}]],
quizPool:[["How old is Bukchon Hanok Village?","About 600 years",["About 600 years","About 60 years","About 6 years"]],["What is a hanok?","A traditional Korean house",["A traditional Korean house","A market","A temple"]],["Real families live in Bukchon today.","true"],["You can walk into any hanok you like.","false"]]},

{id:'insadong',lat:37.5744,lng:126.9856,day:'28 Oct 2026',unlock:'2026-10-28',emoji:'🍚',title:'Insadong & Jogyesa',hotel:'ENA Suite Hotel Namdaemun',loc:'Insadong, Seoul',
facts:['Insadong is Korea’s traditional craft street.','Buddhist temple food here is entirely plant-based.','Jogyesa is the head temple of Korean Buddhism.'],
huntPool:['Find hanji paper.','Photograph the lanterns at Jogyesa.','Find the Ssamziegil spiral building.','Spot a calligraphy brush shop.','Try a temple food dish.','Find a celadon pot.','Spot a tea house.'],
games:[["memory","Temple Food Match",{"icons":["🍚","🥬","🍵","🪷","🥢","🏮"]}],["catch","Lantern Catch",{"good":["🏮","🪷"],"bad":["🦐"],"catcher":"🧺"}],["tap","Lantern Row",{"t":"🏮"}],["timing","Tea Pour",{}],["whack","Shrimp Check",{"mole":"🥬","decoy":"🦐"}]],
quizPool:[["What is Korean Buddhist temple food?","Entirely plant-based cooking",["Entirely plant-based cooking","Barbecue","Seafood stew"]],["What is Jogyesa?","The head temple of Korean Buddhism",["The head temple of Korean Buddhism","A palace","A market"]],["Temple food kimchi has no shrimp in it.","true"],["Insadong is a modern shopping mall.","false"]]},

{id:'gwangjang',lat:37.5701,lng:126.9997,day:'28 Oct 2026',unlock:'2026-10-28',emoji:'🥟',title:'Gwangjang Market',hotel:'ENA Suite Hotel Namdaemun',loc:'Jongno, Seoul',
facts:['Founded in 1905 — one of Seoul’s oldest markets.','Famous for mayak gimbap, tiny "addictive" rice rolls.','Bindaetteok mung bean pancakes are fried in front of you.'],
huntPool:['Eat mayak gimbap.','Watch bindaetteok being fried.','Find the busiest food stall.','Spot a stall selling only one thing.','Find someone eating standing up.','Photograph the whole food alley.','Find a stallholder who has been there for years.'],
games:[["catch","Gimbap Grab",{"good":["🍙","🥬","🥞"],"bad":["🦐"],"catcher":"🧺"}],["whack","Pancake Flip",{"mole":"🥞","decoy":"🦐"}],["tap","Roll the Gimbap",{"t":"🍙"}],["memory","Market Match",{"icons":["🥟","🍙","🥞","🍜","🌶️","🥬"]}],["dice21","Market Dice 21",{}]],
quizPool:[["What is mayak gimbap?","Tiny vegetable seaweed rice rolls",["Tiny vegetable seaweed rice rolls","A spicy stew","A dessert"]],["What is hidden in most restaurant kimchi?","Fermented salted shrimp",["Fermented salted shrimp","Sugar","Cheese"]],["Gwangjang Market was founded in 1905.","true"],["Gwangjang Market takes card everywhere.","false"]]},

{id:'ikseon',lat:37.5742,lng:126.9905,day:'29 Oct 2026',unlock:'2026-10-29',emoji:'☕',title:'Ikseon-dong & Euljiro',hotel:'ENA Suite Hotel Namdaemun',loc:'Jongno, Seoul',
facts:['Ikseon-dong is a 100-year-old hanok area now full of cafés.','Some of its alleys are barely a metre wide.','Euljiro is nicknamed "Hipjiro" — tool shops below, hidden bars above.'],
huntPool:['Find the narrowest alley.','Photograph a hanok that is now a café.','Find an unmarked door or staircase.','Spot a tool or lighting shop in Euljiro.','Find peeling paint that looks deliberate.','Photograph the prettiest café.','Find a sign you cannot read at all.'],
games:[["memory","Alley Match",{"icons":["☕","🏘️","🔧","💡","🍵","🪟"]}],["runner","Alley Dash",{"p":"🏃","o":"🪑"}],["tap","Coffee Pour",{"t":"☕"}],["hl","Café Cards",{}],["timing","Latte Art",{}]],
quizPool:[["What was Euljiro originally famous for?","Printing and lighting supplies",["Printing and lighting supplies","Fishing","Farming"]],["What is Ikseon-dong made of?","Old hanok courtyard houses",["Old hanok courtyard houses","Skyscrapers","Tents"]],["Many Euljiro bars are deliberately unmarked.","true"],["Ikseon-dong was knocked down and rebuilt.","false"]]},

{id:'ddp',lat:37.5665,lng:127.0092,day:'29 Oct 2026',unlock:'2026-10-29',emoji:'🛸',title:'Dongdaemun DDP',hotel:'ENA Suite Hotel Namdaemun',loc:'Dongdaemun, Seoul',
facts:['Zaha Hadid designed it with 45,000 curved aluminium panels.','There is not a single straight line in the building.','The old Seoul city wall was excavated right underneath it.'],
huntPool:['Photograph the silver curves.','Find the excavated old city wall.','Spot the LED rose garden.','Find a shopping tower open past midnight.','Photograph a reflection in the panels.','Find the strangest angle in the building.','Spot a design exhibition.'],
games:[["runner","Curve Runner",{"p":"🛹","o":"🔩"}],["memory","Design Match",{"icons":["🛸","🌹","💡","🏛️","🔷","✨"]}],["timing","Panel Photo",{}],["tap","LED Roses",{"t":"🌹"}],["dodge","Late Night Shoppers",{"p":"🧍","o":"🛍️"}]],
quizPool:[["Who designed the DDP?","Zaha Hadid",["Zaha Hadid","Frank Gehry","Nobody knows"]],["How many aluminium panels cover it?","About 45,000",["About 45,000","About 45","About 4 million"]],["The DDP has no straight lines.","true"],["Dongdaemun shops all close at 6pm.","false"]]},

{id:'hongdae',lat:37.5563,lng:126.9236,day:'29 Oct 2026',unlock:'2026-10-29',emoji:'🎤',title:'Hongdae Busking',hotel:'ENA Suite Hotel Namdaemun',loc:'Mapo, Seoul',
facts:['Hongdae is Seoul’s university and youth-culture district.','From about 5pm the street fills with buskers and dance crews.','It is 7 minutes from our hotel on the AREX line.'],
huntPool:['Watch a K-pop dance crew properly.','Find a claw machine hall.','Photograph a busking crowd.','Find K-pop merchandise.','Spot a theme café.','Find the Gyeongui Line Forest Park.','Join in or clap for a busker.'],
games:[["simon","Dance Moves",{}],["tap","Crowd Clap",{"t":"👏"}],["memory","K-pop Match",{"icons":["🎤","🎧","💿","🕺","✨","🎸"]}],["whack","Claw Machine",{"mole":"🧸","decoy":"🪙"}],["catch","Merch Grab",{"good":["💿","🎧","🧸"],"bad":["🗑️"],"catcher":"🎒"}]],
quizPool:[["What happens in Hongdae from about 5pm?","Street busking",["Street busking","Everything closes","A parade"]],["Why is Hongdae last on this day?","It is the closest district to the hotel by train",["It is the closest district to the hotel by train","It opens latest","It is the cheapest"]],["Hongdae is a university district.","true"],["Busking in Hongdae costs money to watch.","false"]]},

{id:'seongsu',lat:37.5445,lng:127.0557,day:'30 Oct 2026',unlock:'2026-10-30',emoji:'🧱',title:'Seongsu-dong',hotel:'ENA Suite Hotel Namdaemun',loc:'Seongdong, Seoul',
facts:['Nicknamed "the Brooklyn of Seoul".','It was Seoul’s shoe-manufacturing district.','The old red-brick factories are now cafés and flagship stores.'],
huntPool:['Photograph exposed brickwork.','Find Daelim Changgo, the old rice warehouse café.','Spot a pop-up store.','Find a handmade shoe shop.','Photograph a steel beam left on show.','Find the most Instagram-looking corner.','Spot something that opened this month.'],
games:[["runner","Warehouse Run",{"p":"🏃","o":"📦"}],["memory","Brick Match",{"icons":["🧱","☕","👟","🏭","🎨","🪟"]}],["tap","Espresso Shot",{"t":"☕"}],["timing","Latte Art",{}],["hl","Pop-up Cards",{}]],
quizPool:[["What did Seongsu-dong used to make?","Shoes",["Shoes","Cars","Paper"]],["What is Daelim Changgo?","A converted rice warehouse café",["A converted rice warehouse café","A train station","A palace"]],["Seongsu is nicknamed the Brooklyn of Seoul.","true"],["All the old factories were demolished.","false"]]},

{id:'coex',lat:37.5115,lng:127.0595,day:'30 Oct 2026',unlock:'2026-10-30',emoji:'📚',title:'Starfield Library · COEX',hotel:'ENA Suite Hotel Namdaemun',loc:'Gangnam, Seoul',
facts:['13-metre-high bookshelves holding around 85,000 books.','It sits inside Asia’s largest underground shopping mall.','SMTOWN COEX Artium next door is the K-pop building.'],
huntPool:['Photograph the giant bookshelves.','Find a book you recognise.','Spot the Gangnam Style hands statue.','Find the K-pop merchandise floor.','Photograph the whole atrium.','Find the biggest shop in the mall.','Spot someone reading.'],
games:[["catch","Book Drop",{"good":["📚","📖"],"bad":["☕"],"catcher":"🤲"}],["memory","Library Match",{"icons":["📚","📖","🎤","💿","🐧","🕺"]}],["tap","Shelf Stack",{"t":"📚"}],["whack","Find the Book",{"mole":"📕","decoy":"☕"}],["hl","Library Cards",{}]],
quizPool:[["How tall are the Starfield Library shelves?","13 metres",["13 metres","3 metres","50 metres"]],["What is SMTOWN COEX Artium?","A K-pop building with merch and exhibits",["A K-pop building with merch and exhibits","A library","A cinema"]],["The Starfield Library is free to walk around.","true"],["COEX is a small corner shop.","false"]]},

{id:'seoulsky',lat:37.5125,lng:127.1025,day:'30 Oct 2026',unlock:'2026-10-30',emoji:'🌆',title:'Seoul Sky · Lotte Tower',hotel:'ENA Suite Hotel Namdaemun',loc:'Jamsil, Seoul',
facts:['555 metres and 123 floors — the world’s fifth-tallest building.','The Sky Deck at 478m has a glass floor you stand on.','Its lift is one of the fastest on Earth.'],
huntPool:['Stand on the glass floor.','Photograph the Han River from above.','Find the fastest lift sign.','Spot the sunset.','Find the highest point you can reach.','Photograph Seoul lit up at night.','Spot Lotte World below.'],
games:[["timing","Sunset Snap",{}],["dodge","Glass Floor Nerves",{"p":"🧍","o":"💨"}],["runner","Lift Race",{"p":"🛗","o":"🏗️"}],["memory","Skyline Match",{"icons":["🌆","🏙️","🌃","🌉","✨","🗼"]}],["reels","Neon Lights",{"icons":["🌆","🏙️","✨","🌃","⭐"]}]],
quizPool:[["How tall is Lotte World Tower?","555 metres",["555 metres","123 metres","1,000 metres"]],["How high is the glass-floored Sky Deck?","478 metres",["478 metres","100 metres","555 metres"]],["Lotte World Tower is the world’s fifth-tallest building.","true"],["The glass floor is at ground level.","false"]]},

{id:'banpo',lat:37.5113,lng:126.9959,day:'30 Oct 2026',unlock:'2026-10-30',emoji:'🌈',title:'Banpo Rainbow Fountain',hotel:'ENA Suite Hotel Namdaemun',loc:'Banpo Bridge, Seoul',
facts:['The world’s longest bridge fountain — 1,140 metres.','380 jets and 200 lights fire in time to music.','The season ends on 31 October, so we catch it just in time.'],
huntPool:['Photograph the fountain mid-show.','Find the best viewing spot in the park.','Spot the colours changing.','Photograph the Han River at night.','Find someone filming the whole show.','Spot a bridge light reflection in the water.','Find the quietest place to watch.'],
games:[["timing","Fountain Photo",{}],["catch","Water Jets",{"good":["💧","🌈"],"bad":["🪨"],"catcher":"☂️"}],["memory","Rainbow Match",{"icons":["🌈","💧","🌉","🎶","🌃","✨"]}],["simon","Music Sync",{}],["tap","Jet Spray",{"t":"💧"}]],
quizPool:[["How long is the Banpo bridge fountain?","1,140 metres",["1,140 metres","114 metres","11 kilometres"]],["What stops the show running?","Rain or strong wind",["Rain or strong wind","Too many people","Cold weather"]],["The fountain runs in time to music.","true"],["The fountain runs all year round.","false"]]},

{id:'home',lat:37.4602,lng:126.4407,day:'31 Oct 2026',unlock:'2026-10-31',emoji:'🎃',title:'Halloween Homeward',hotel:'Home!',loc:'Incheon → London',
facts:['We fly home on Halloween and land at 16:30.','Korean Air leaves from Incheon Terminal 2 — the opposite of Narita.','Back in time for the trick-or-treaters.'],
huntPool:['Find the departure board showing London.','Photograph your favourite souvenir.','Find something you bought in both countries.','Spot the last Hangul sign you will see.','Take a final family photo.','Find breakfast at Incheon.','Photograph the plane taking you home.'],
games:[["memory","Trip Memories",{"icons":["⛩️","🗼","🏰","🌈","🍣","🎃"]}],["catch","Souvenir Sort",{"good":["🎁","🧸","🍡"],"bad":["🧾"],"catcher":"🧳"}],["runner","Final Dash",{"p":"🧳","o":"🚧"}],["wheel","Duty Free Wheel",{}],["dice21","Final Dice 21",{}]],
quizPool:[["Which Incheon terminal does Korean Air use?","Terminal 2",["Terminal 2","Terminal 1","Terminal 3"]],["What day do we land home?","Halloween",["Halloween","Christmas","New Year"]],["We land back at Heathrow the same day we take off.","true"],["We fly home from Tokyo.","false"]]}
];

/* ===== V3 DATA ===== */
const STOP_COORDS={};STOPS.forEach(s=>{STOP_COORDS[s.id]=[s.lat,s.lng];});
const HEADSUP_PACKS={
'Japan & Korea':['TORII GATE','BULLET TRAIN','SUSHI','RAMEN','MOUNT FUJI','NEON SIGN','TEMPLE','KIMONO','VENDING MACHINE','SUMO','KARAOKE','K-POP','KIMCHI','PALACE','MONKEY','CHOPSTICKS','GEISHA','SHRINE','ARCADE','SKYSCRAPER','CHERRY BLOSSOM','BAMBOO','HANBOK','MATCHA','LANTERN','SUBWAY','NINJA','SAMURAI','ROBOT','CONVENIENCE STORE'],
'Animals':['DEER','FOX','MONKEY','CRANE','KOI CARP','TANUKI','CAT','SHIBA INU','PANDA','OWL','TURTLE','DRAGON','SNAKE','EAGLE','PENGUIN','RABBIT','BEAR','FROG','SQUIRREL','JELLYFISH'],
'Films & Fun':['POKEMON','MARIO','ZELDA','TOTORO','GODZILLA','ANIME','MINECRAFT','FORTNITE','ROBLOX','TIKTOK','YOUTUBE','SPIDERMAN','BATMAN','FROZEN','DISNEY','STAR WARS','SONIC','DEMON SLAYER','ONE PIECE','NARUTO'],
'Family':['JACOB','LILY','HANNAH','ETHAN','MOCHI THE CAT','MUM','DAD','SNORING','JET LAG','ARE WE THERE YET','LOST LUGGAGE','SUITCASE','SUNCREAM','ICE CREAM','SELFIE','HOTEL POOL','BREAKFAST BUFFET','WINDOW SEAT','TRAVEL PILLOW','SOUVENIR']};
const ROUTE_QUIZ=[
['How tall is Tokyo Skytree?',['634 metres','300 metres','1,000 metres','100 metres'],0],
['What year was Senso-ji founded?',['645 AD','1645','1945','1245'],0],
['What animal is Inari’s messenger?',['The fox','The deer','The crane','The bear'],0],
['Which is the world’s busiest railway station?',['Shinjuku','Tokyo Station','Seoul Station','Kyoto Station'],0],
['How many Kannon statues are in Sanjusangen-do?',['1,001','101','11','10,001'],0],
['What do nightingale floors do?',['Chirp when walked on','Glow','Move','Nothing'],0],
['Which festival is on 22 October in Kyoto?',['Jidai Matsuri','Gion Matsuri','Obon','Tanabata'],0],
['How tall is Lotte World Tower?',['555 metres','123 metres','300 metres','1,000 metres'],0],
['What is hanbok?',['Traditional Korean dress','A Korean soup','A palace','A train'],0],
['What is hidden in most Korean kimchi?',['Salted shrimp','Sugar','Cheese','Beef'],0],
['What is a konbini?',['A convenience store','A temple','A train','A market'],0],
['Where did the Tokyo fish market move to in 2018?',['Toyosu','Kyoto','Odaiba','Ueno'],0],
['What is Nishiki Market nicknamed?',['Kyoto’s Kitchen','Tokyo’s Garden','Seoul’s Table','Osaka’s Pantry'],0],
['Who built Nijo Castle?',['Tokugawa Ieyasu','Emperor Meiji','Oda Nobunaga','Hideyoshi'],0],
['What is the Korean alphabet called?',['Hangul','Kanji','Hiragana','Katakana'],0],
['Which park is unique to Tokyo?',['DisneySea','Disneyland','Epcot','Magic Kingdom'],0],
['What do you do before entering teamLab Planets?',['Take your shoes off','Put a hat on','Sing','Pay again'],0],
['Which bridge has the Rainbow Fountain?',['Banpo Bridge','Rainbow Bridge','Tower Bridge','Golden Gate'],0],
['What speed does the Nozomi reach?',['285 km/h','100 km/h','500 km/h','60 km/h'],0],
['Which palace is Korea’s main royal palace?',['Gyeongbokgung','Changdeokgung','Nijo','Buckingham'],0],
['What is a hanok?',['A traditional Korean house','A Korean noodle','A shrine','A shop'],0],
['How many torii gates are at Fushimi Inari?',['Thousands','Ten','Fifty','One'],0],
['What is mayak gimbap?',['Tiny vegetable rice rolls','Spicy stew','Fried chicken','A dessert'],0],
['Which city has Bukchon Hanok Village?',['Seoul','Tokyo','Kyoto','Busan'],0],
['What is Akihabara known as?',['Electric Town','Old Town','Water Town','Sky Town'],0],
['Where is the glass-floored Sky Deck?',['Lotte World Tower','Tokyo Skytree','Shibuya Sky','DDP'],0],
['Who designed the DDP in Seoul?',['Zaha Hadid','Frank Gehry','Tadao Ando','Norman Foster'],0],
['What kind of monkeys are at Iwatayama?',['Japanese macaques','Chimpanzees','Gorillas','Lemurs'],0],
['What is Kappabashi famous for?',['Fake food and knives','Cars','Books','Shoes'],0],
['Which airline are we flying?',['Korean Air','ANA','JAL','BA'],0],
['What is an ekiben?',['A station lunch box','A train ticket','A shrine','A game'],0],
['What is Seongsu-dong nicknamed?',['The Brooklyn of Seoul','Little Tokyo','Old Town','Silicon Valley'],0],
['Which day do we fly home?',['Halloween','Christmas','Bonfire Night','New Year'],0],
['What is Ameyoko?',['An old market under the railway','A temple','A palace','A tower'],0]];
const EMOJI_RIDDLES=[['⛩️🦊🔴','fushimi inari'],['🗼6️⃣3️⃣4️⃣','tokyo skytree'],['🚦👥👥','shibuya crossing'],['🎨💧👣','teamlab planets'],['🎋🐒🌉','arashiyama'],['🏯🎵👣','nijo castle'],['🐟🍣🌅','tsukiji market'],['👘🏯🇰🇷','gyeongbokgung'],['🌈💧🌉','banpo fountain'],['🚄🗻🍱','shinkansen'],['🎌🎮💡','akihabara'],['🏰🌊🌋','disneysea']];
const WORDLE_WORDS=['TOKYO','KYOTO','SEOUL','SUSHI','RAMEN','TORII','SHRINE'.slice(0,5),'NEONS','BULLET'.slice(0,5),'MOCHI','UDONS','MATCHA'.slice(0,5),'TEMPLE'.slice(0,5),'KIMCHI'.slice(0,5),'HOTEL','TRAIN','PLANE','NIGHT','LIGHT','TOWER','CASTLE'.slice(0,5),'SNACK','JUICE','PHOTO','QUEST','STOPS','PRIZE','CROWN','CHAMP','SPINS','CHIPS','BONUS','COINS','STARS','MONKEY'.slice(0,5),'FOXES','DEERS','PANDA','DRAGON'.slice(0,5),'RIVER','OCEAN','SANDS','CLOUD','BAMBO','LOTUS','CRANE','PEARL','JEWEL','SILKY','FUJIS'];
